---
# Applications
applications:
  servers:
    restapi:
      options:
        showEngineHeader: true
        displayOpenAPI: true
        hostname: "http://localhost"
        listener:
          port: 8080
        middlewares:
          logger:
            enable: true
        openAPIDefinition: # OpenAPIDefinition
          info:
            title: "KoreServe REST API Server"
            description: "KoreServe Main API Definition."
            version: 0.1.0
            basePath: "/api/v1"

# Databases
databases:
  identityDB:
    connectionName: "db-identity"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "gorm"
    password: "gorm"
    hostName: "127.0.0.1:3306" # hostname:port OR path
    dbName: "koreserve"
    config: "charset=utf8&parseTime=True&loc=Local"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production
  mainDB:
    connectionName: "db-main"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "gorm"
    password: "gorm"
    hostName: "127.0.0.1:3306" # hostname:port OR path
    dbName: "koreserve"
    config: "charset=utf8&parseTime=True&loc=Local"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production
  # logDB:
  #   connectionName: "db-log"
  #   driver: "mysql" # mysql, postgres, sqlserver, sqlite3
  #   # mysql
  #   username: "gorm"
  #   password: "gorm"
  #   hostName: "127.0.0.1:3306" # hostname:port OR path
  #   dbName: "a_d3ta_logs"
  #   config: "charset=utf8&parseTime=True&loc=Local"
  #   maxIdleConns: 10
  #   maxOpenConns: 10
  #   logMode: true # shoud be "false" on production
  emailDB:
    connectionName: "db-email"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "gorm"
    password: "gorm"
    hostName: "127.0.0.1:3306" # hostname:port OR path
    dbName: "koreserve"
    config: "charset=utf8&parseTime=True&loc=Local"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production

# IAM
IAM:
  defaultAdmin:
    username: "admin.koreserve"
    password: "koreserve"
    nickName: "super admin"
    email: "koreserve.acornsoft@gmail.com"
    authorityID: "group:admin"
  registration:
    activationURL: "http://%s/api/v1/auths/registration/activate"
    defaultAuthorityID: "group:default"
  JWT:
    issuer: "KORESERVE"
    signingKey: "KORESERVE-SigningKey"
  casbin:
    modelPath: "casbin/casbin_rbac_rest_model.conf"
    enforcers:
      defaultEnforcerID: "default-casbin-enforcer"
      systemEnforcerID: "system-casbin-enforcer"

# securities
# securities:
#   captcha:
#     keyLong: 4
#     imgWidth: 120
#     imgHeight: 40
#     imgUrl: "http://%s/system/captcha/image/%s.png"

# Directory Locations
dirLocations:
  conf: "./conf"
  www: "./www"
  temp: "./temp"
  log: "./logs"
  cache: "./caches"
  modelPackageFileRootPath: "koreserve-modelpackage"
  modelPath: "/model"
  trainingDatasetPath: "/training-dataset"
  holdoutDatasetPath: "/holdout-dataset"
  monitoringFileRootPath: "koreserve-monitoring"
  actualDataPath: "/actual-data"

connectors:
  storages:
    minio:
      endpoint: "192.168.88.154:9000"
      accessKeyID: "minioadmin"
      secretAccessKey: "minioadmin"
      useSSL: false
  driftServer:
    endpoint: "http://192.168.88.151:30071"
  accuracyServer:
    endpoint: "http://192.168.88.151:30072"
  graphServer:
    endpoint: "http://192.168.88.151:30073"
  kafka:
    endpoint: "192.168.88.151:32038"
    groupID: "monitor-group"
    autoOffsetReset: "latest"




# SMTP Servers
SMTPServers:
  defaultSMTP:
    server: "smtp.gmail.com"
    port: "587"
    username: "koreserve.acornsoft@gmail.com"
    password: "coqaxngvrbrhzset"
    senderEmail: "koreserve.acornsoft@gmail.com"
    senderName: "KoreServe NoReply"

# Caches
caches:
  # Cache with Redis engine Sample
  sessionCache:
    connectionName: "session-cache"
    engine: "redis"
    driver: "redis"
    configurations: # Following redis engine
      network: "tcp"
      host: "127.0.0.1"
      port: "6379"
      username: ""
      password: ""
      db: 1
      maxRetries: 3
      poolSize: 10
      minIdleConns: 5
  # Cache with GoMacaron/Cache engine Sample
  # tmpDataCache:
  #   connectionName: "tmp-data-cache"
  #   engine: "gomacaron"
  #   driver: "redis"
  #   configurations: # Following GoMacaron/Cache engine
  #     adapter: "redis"
  #     adapterConfig: "addr:127.0.0.1:6379"
  #     interval: 60
  #     occupyMode: false
  #     section: "cache"

