---
# Applications
applications:
  servers:
    restapi:
      options:
        showEngineHeader: true
        displayOpenAPI: true
        hostname: "http://localhost:8080"
        listener:
          port: 8080
        middlewares:
          logger:
            enable: true
        openAPIDefinition: # OpenAPIDefinition
          info:
            title: "KoreServe REST API Server"
            description: "1. Swagger 문서 좌측 상단 Schemes를 HTTPS로 선택 \n 2. Swagger 문서 Auth 섹션에서 register API를 이용해 user를 생성\n3. 등록된 email로 인증메일 전송되며 인증 진행  \n4. Swagger 문서 Auth 섹션 login API 이용 로그인 진행\n5. 응답으로 전달 된 JWT token 을 Swagger API 문서 우측 상단 Authorize 아이콘 클릭 후 입력\n    예) bearer eyJhb......NsNTCCPTeBsOvv6Q4  \n    *bearer는 수기입력 필수\n6. Create Project API 호출 \n7. Create ModelPackage API 호출(생성 된 projectID 입력) 및 Model/TrainingDataset/HoldeOutDataset 업로드 진행(dataset은 csv 포맷으로 feature명칭/Target값 포함 필수)\n8. Create Deployment API 호출(생성 된 modelPackageID 입력)\n9. Deployment Send Prediction API 로 예측확인\n10. Noti섹션 Create Web-Hook API호출(Deployment의 Datadrift/Acuuracy 상태 변경시 호출 될 PipeLine Client정보 저장)"
            version: 0.2
            basePath: "/api/v1"

# Databases
databases:
  identityDB:
    connectionName: "db-identity"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "gorm"
    password: "gorm"
    hostName: "mariadb" # hostname:port OR path
    dbName: "koreserve"
    config: "charset=utf8&parseTime=True&loc=UTC"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production
  mainDB:
    connectionName: "db-main"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "gorm"
    password: "gorm"
    hostName: "mariadb" # hostname:port OR path
    dbName: "koreserve"
    config: "charset=utf8&parseTime=True&loc=UTC"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: false # shoud be "false" on production
  emailDB:
    connectionName: "db-email"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "gorm"
    password: "gorm"
    hostName: "mariadb" # hostname:port OR path
    dbName: "koreserve"
    config: "charset=utf8&parseTime=True&loc=UTC"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production

# IAM
IAM:
  defaultAdmin:
    username: "admin.koreserve"
    password: "koreserve"
    nickName: "super admin"
    email: "user@example.com"
    authorityID: "group:admin"
  defaultUser:
    username: "user.infinov"
    password: "infinov"
    nickName: "user of infinov"
    email: "user@example.com"
    authorityID: "group:default"
  registration:
    activationURL: "http://%s/api/v1/auths/registration/activate"
    defaultAuthorityID: "group:default"
  JWT:
    issuer: "KORESERVE"
    signingKey: "KORESERVE-SigningKey"

# Directory Locations
dirLocations:
  conf: "./conf"
  www: "./www"
  temp: "./temp"
  log: "./logs"
  cache: "./caches"
  modelPackageFileRootPath: "koreserve-modelpackage"
  modelPath: "/model"
  trainingDatasetPath: "/training-dataset"
  holdoutDatasetPath: "/holdout-dataset"
  monitoringFileRootPath: "koreserve-monitoring"
  actualDataPath: "/actual-data"

# MicroService & ThirdParty Services
connectors:
  storages:
    minio:
      endpoint: "minio"
      accessKeyID: "minioadmin"
      secretAccessKey: "minioadmin"
      useSSL: false
  driftServer:
    endpoint: "http://drift-monitor"
  accuracyServer:
    endpoint: "http://accuracy-monitor"
  serviceHealthServer:
    endpoint: "http://service-monitor"
  graphServer:
    endpoint: "http://graph-server"
  kafka:
    endpoint: "kafka:"
    groupID: "monitor-group-t"
    autoOffsetReset: "latest"
  inferenceSvc:
    kserveAPISvrEndPoint: "http://kserve-api"
    kserveHostName: "example.com"
    kserveIngressEndPoint: "http://istio-ingress"
    inferenceNamespace: "koreserve"

# SMTP Servers
SMTPServers:
  defaultSMTP:
    server: "smtp.example.com"
    port: "587"
    username: "user@example.com"
    password: "password"
    senderEmail: "user@example.com"
    senderName: "User NoReply"
