// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/project/{projectID}/models": {
            "post": {
                "description": "Create model's info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create model",
                "parameters": [
                    {
                        "description": "name of the model",
                        "name": "modelBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PostModelsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PostModelsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.PostModelsRequest": {
            "type": "object",
            "properties": {
                "classLabels": {
                    "description": "멀티클래스분류 일때 라벨",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "negativeClassLabel": {
                    "description": "이진분류시 거짓값 라벨",
                    "type": "string"
                },
                "positiveClassLabel": {
                    "description": "이진분류시 참값 라벨",
                    "type": "string"
                },
                "predictionThreshold": {
                    "description": "이진분류 모델의 결과가 확률일 때 이진 범주에 매핑",
                    "type": "string"
                },
                "targetType": {
                    "description": "Required [‘Binary’, ‘Regression’, ‘Multiclass’, ‘Anomaly’, ‘Transform’, ‘Unstructured’]",
                    "type": "string"
                }
            }
        },
        "http.PostModelsResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:30000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "KoreServ Swagger API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
