// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auths/login": {
            "post": {
                "description": "유저 로그인",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "login user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResDTO"
                        }
                    }
                }
            }
        },
        "/auths/register": {
            "post": {
                "description": "유저 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "register user",
                "parameters": [
                    {
                        "description": "register user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterReqDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterResDTO"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor": {
            "get": {
                "description": "모니터 설정 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get Monitor Setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MonitorGetSettingResponseDTO"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor/accuracy": {
            "get": {
                "description": "정확도 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get Accuracy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "modelHistoryID",
                        "name": "modelHistoryID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "timeline or aggregation",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-05-05:01",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-08-01:01",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AccuracyGetResponseDTO"
                        }
                    }
                }
            },
            "patch": {
                "description": "정확도 모니터링 설정 변경",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Patch Accuracy Monitor Setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch Accuracy Monitor",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MonitorAccuracyPatchRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MonitorAccuracyPatchResponseDTO"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor/actual": {
            "post": {
                "description": "upload Actual file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Upload Actual file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "actual file upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "target column name",
                        "name": "targetLabel",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadActualResponseDTO"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor/association-id": {
            "patch": {
                "description": "AssociationID 패치, 변경이전의 Association ID로 예측한 데이터들은 사용 불가능 합니다. 테스트용 삭제예정.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Patch AssociationID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch AssociationID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAssociationIDRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAssociationIDResponseDTO"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor/detail": {
            "get": {
                "description": "피쳐 드리프트 디테일",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get Feature Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "modelHistoryID",
                        "name": "modelHistoryID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-05-05:01",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-05-05:01",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FeatureDriftGetResponseDTO"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor/drift": {
            "get": {
                "description": "데이터 드리프트",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get Data Drift",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "modelHistoryID",
                        "name": "modelHistoryID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-05-05:01",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-08-01:01",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FeatureDriftGetResponseDTO"
                        }
                    }
                }
            },
            "patch": {
                "description": "드리프트 모니터링 설정 변경",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Patch Drift Monitor Setting",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch Drift Setting",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MonitorDriftPatchRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.MonitorDriftPatchResponseDTO"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor/graph/detail": {
            "get": {
                "description": "피쳐 디테일 그래프",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get Feature Detail Graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "modelHistoryID",
                        "name": "modelHistoryID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-05-05:01",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-08-01:01",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deployments/{deploymentID}/monitor/graph/drift": {
            "get": {
                "description": "드리프트 그래프",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Monitor"
                ],
                "summary": "Get Drift Graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "modelHistoryID",
                        "name": "modelHistoryID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-05-05:01",
                        "name": "startTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "example=2022-08-01:01",
                        "name": "endTime",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments": {
            "get": {
                "description": "배포 리스트",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Get Deployment List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "queryName",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetDeploymentListResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "배포 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Create Deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create Deployment",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateDeploymentRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateDeploymentResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments/{deploymentID}": {
            "get": {
                "description": "배포 상세조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Get Deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetDeploymentResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "배포 삭제",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Delete Deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteDeploymentResponseDTO"
                        }
                    }
                }
            },
            "patch": {
                "description": "배포 정보수정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Edit Deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Deployment Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateDeploymentRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateDeploymentResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments/{deploymentID}/active": {
            "put": {
                "description": "배포 활성화",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Active Deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ActiveDeploymentResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments/{deploymentID}/governance-log": {
            "get": {
                "description": "배포 거버넌스 로그 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Get Governance Log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetGovernanceHistoryResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments/{deploymentID}/inactive": {
            "put": {
                "description": "배포 비활성화",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Inactive Deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.InActiveDeploymentResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments/{deploymentID}/model-history": {
            "get": {
                "description": "배포 모델 변경이력 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Get Model History",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetModelHistoryResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments/{deploymentID}/predict": {
            "post": {
                "description": "예측 요청",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Send Prediction",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "application/json",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "{\n\"association_id\": [\"abcd1234\", \"abcd1235\"], \n\"instances\": [[1.483887, 1.865988, 2.234620, 1.018782, -2.530891, -1.604642, 0.774676, -0.465148, -0.495225], [1.483887, 1.865988, 2.234620, 1.018782, -2.530891, -1.604642, 0.774676, -0.465148, -0.495225]]\n}"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReplaceModelResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/deployments/{deploymentID}/replace-model": {
            "patch": {
                "description": "배포 모델변경",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployment"
                ],
                "summary": "Replace Model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "deploymentID",
                        "name": "deploymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create Deployment",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ReplaceModelRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReplaceModelResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/model-packages": {
            "get": {
                "description": "모델 패키지 리스트",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Get ModelPackage List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "queryName",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sort",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetModelPackageListResponseDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "모델 패키지 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Create ModelPackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create ModelPackage",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateModelPackageRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateModelPackageResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}": {
            "get": {
                "description": "모델 패키지 상세조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Get ModelPackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetModelPackageResponseDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "모델 패키지 삭제",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Delete ModelPackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.DeleteModelPackageResponseDTO"
                        }
                    }
                }
            },
            "patch": {
                "description": "모델 패키지 정보수정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Edit ModelPackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update ModelPackage Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateModelPackageRequestDTO"
                        }
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateModelPackageResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}/archive": {
            "put": {
                "description": "모델 패키지 보관",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Archive ModelPackage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ArchiveModelPackageResponseDTO"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}/download-holdout-dataset": {
            "get": {
                "description": "홀드아웃 데이터셋 파일 다운로드",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Download Holdout Dataset File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}/download-model": {
            "get": {
                "description": "모델 파일 다운로드",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Download Model File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}/download-training-dataset": {
            "get": {
                "description": "훈련 데이터셋 파일 다운로드",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Download Training Dataset File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}/upload-holdout-dataset": {
            "post": {
                "description": "훈련 검증 데이터셋 파일 업로드",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Upload Holdout Dataset File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file upload",
                        "name": "upfile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}/upload-model": {
            "post": {
                "description": "모델 파일 업로드",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Upload Model File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file upload",
                        "name": "upfile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/projects/{projectID}/model-packages/{modelPackageID}/upload-training-dataset": {
            "post": {
                "description": "훈련 데이터셋 파일 업로드",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ModelPackage"
                ],
                "summary": "Upload Training Dataset File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "projectID",
                        "name": "projectID",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "modelPackageID",
                        "name": "modelPackageID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "file upload",
                        "name": "upfile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "dto.AccuracyGetResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "결과 message",
                    "type": "string",
                    "x-order": "0"
                },
                "data": {
                    "description": "응답 결과 data",
                    "type": "string",
                    "x-order": "1"
                },
                "startTime": {
                    "description": "검색 시작 시간",
                    "type": "string",
                    "x-order": "2"
                },
                "endTIme": {
                    "description": "검색 끝 시간",
                    "type": "string",
                    "x-order": "3"
                }
            }
        },
        "dto.AccuracySetting": {
            "type": "object",
            "properties": {
                "metricType": {
                    "description": "Accuracy 측정 메트릭 종류",
                    "type": "string",
                    "enum": [
                        "rmse",
                        " rmsle",
                        " mae",
                        " mad",
                        " mape",
                        " mean_tweedie_deviance",
                        " gamma_deviance",
                        " tpr",
                        " accuracy",
                        " f1",
                        " ppv",
                        " fnr",
                        " fpr"
                    ],
                    "x-order": "0",
                    "example": "rmse"
                },
                "measurement": {
                    "description": "메트릭 Value 타입",
                    "type": "string",
                    "enum": [
                        "percent",
                        " value"
                    ],
                    "x-order": "1",
                    "example": "percent"
                },
                "atRiskValue": {
                    "description": "메트릭의 AtRisk Value",
                    "type": "number",
                    "x-order": "2",
                    "example": 5
                },
                "failingValue": {
                    "description": "메트릭의 Failing Value",
                    "type": "number",
                    "x-order": "3",
                    "example": 10
                }
            }
        },
        "dto.ActiveDeploymentResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.ArchiveModelPackageResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.CreateDeploymentRequestDTO": {
            "type": "object",
            "required": [
                "modelPackageID",
                "name",
                "predictionEnvID"
            ],
            "properties": {
                "modelPackageID": {
                    "description": "모델패키지 ID",
                    "type": "string",
                    "x-order": "1 x-nullable=false",
                    "example": "ID-1234"
                },
                "name": {
                    "description": "배포 명",
                    "type": "string",
                    "x-order": "2 x-nullable=false",
                    "example": "This Is a Test Deploy"
                },
                "description": {
                    "description": "배포 설명",
                    "type": "string",
                    "x-order": "3",
                    "example": "deploy best model"
                },
                "predictionEnvID": {
                    "description": "예측 환경",
                    "type": "string",
                    "x-order": "4",
                    "example": "k8s-inference-staging"
                },
                "importance": {
                    "description": "배포중요도",
                    "type": "string",
                    "enum": [
                        "Low",
                        " Moderate",
                        " High",
                        " Critical"
                    ],
                    "x-order": "5",
                    "example": "Low"
                },
                "requestCPU": {
                    "description": "요청 CPU",
                    "type": "number",
                    "x-order": "6",
                    "example": 1
                },
                "requestMEM": {
                    "description": "요청 MEM",
                    "type": "number",
                    "x-order": "7",
                    "example": 2
                },
                "featureDriftTracking": {
                    "description": "데이터 드리프트 설정",
                    "type": "string",
                    "x-order": "8",
                    "example": "True"
                },
                "accuracyAnalyze": {
                    "description": "정확도 측정 설정",
                    "type": "string",
                    "x-order": "9",
                    "example": "True"
                },
                "associationID": {
                    "description": "요청데이터에서 ID로 처리할 유일한 피쳐컬럼 명",
                    "type": "string",
                    "x-order": "9",
                    "example": "Index"
                }
            }
        },
        "dto.CreateDeploymentResponseDTO": {
            "type": "object",
            "properties": {
                "deploymentID": {
                    "type": "string"
                }
            }
        },
        "dto.CreateModelPackageRequestDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "모델패키지 명",
                    "type": "string",
                    "x-order": "1",
                    "example": "ModelPacakge 01"
                },
                "predictionThreshold": {
                    "description": "이진분류 예측임계값",
                    "type": "number",
                    "x-order": "10",
                    "example": 0.5
                },
                "positiveClassLabel": {
                    "description": "이진분류 양성명칭 지정",
                    "type": "string",
                    "x-order": "11",
                    "example": "True"
                },
                "negativeClassLabel": {
                    "description": "이진분류 음성명칭 지정",
                    "type": "string",
                    "x-order": "12",
                    "example": "False"
                },
                "description": {
                    "description": "모델패키지 설명",
                    "type": "string",
                    "x-order": "2",
                    "example": "New ModelPacakge"
                },
                "modelName": {
                    "description": "모델명",
                    "type": "string",
                    "x-order": "3",
                    "example": "Example Model"
                },
                "modelVersion": {
                    "description": "모델 버전",
                    "type": "string",
                    "x-order": "4",
                    "example": "1.4"
                },
                "modelDescription": {
                    "description": "모델 설명",
                    "type": "string",
                    "x-order": "5",
                    "example": "Best Accuracy"
                },
                "targetType": {
                    "description": "모델 예측타입",
                    "type": "string",
                    "enum": [
                        "Binary",
                        " Regression"
                    ],
                    "x-order": "6",
                    "example": "Binary"
                },
                "predictionTargetName": {
                    "description": "예측 타켓명칭",
                    "type": "string",
                    "x-order": "7",
                    "example": "Target"
                },
                "modelFrameWork": {
                    "description": "모델 프레임워크",
                    "type": "string",
                    "enum": [
                        "TensorFlow",
                        " PyTorch",
                        " SkLearn",
                        " XGBoost",
                        " LightGBM"
                    ],
                    "x-order": "8",
                    "example": "TensorFlow"
                },
                "modelFrameWorkVersion": {
                    "description": "모델 프레임워크 버전",
                    "type": "string",
                    "x-order": "9",
                    "example": "1.14.0"
                }
            }
        },
        "dto.CreateModelPackageResponseDTO": {
            "type": "object",
            "properties": {
                "modelPackageID": {
                    "type": "string"
                }
            }
        },
        "dto.DataDriftSetting": {
            "type": "object",
            "properties": {
                "monitorRange": {
                    "description": "Monitoring 할 범위",
                    "type": "string",
                    "x-order": "0",
                    "example": "7d"
                },
                "driftMetricType": {
                    "description": "DataDrift 측정 Metric",
                    "type": "string",
                    "x-order": "1",
                    "example": "PSI"
                },
                "driftThreshold": {
                    "description": "Drift 값 임계치",
                    "type": "number",
                    "x-order": "2",
                    "example": 0.15
                },
                "importanceThreshold": {
                    "description": "Importance 값 임계치",
                    "type": "number",
                    "x-order": "3",
                    "example": 0.5
                },
                "lowImportanceAtRiskCount": {
                    "description": "낮은 importance feature 수의 drift at risk 임계치",
                    "type": "integer",
                    "x-order": "4",
                    "example": 1
                },
                "lowImportanceFailingCount": {
                    "description": "낮은 importance feature 수의 drift failing 임계치",
                    "type": "integer",
                    "x-order": "5",
                    "example": 0
                },
                "highImportanceAtRiskCount": {
                    "description": "높은 importance feature 수의 drift at risk 임계치",
                    "type": "integer",
                    "x-order": "6",
                    "example": 0
                },
                "highImportanceFailingCount": {
                    "description": "높은 importance feature 수의 drift failing 임계치",
                    "type": "integer",
                    "x-order": "7",
                    "example": 1
                }
            }
        },
        "dto.DeleteDeploymentResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.DeleteModelPackageResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.FeatureDriftGetResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message",
                    "type": "string",
                    "x-order": "0"
                },
                "data": {
                    "description": "Feature Drift 결과 Data",
                    "type": "string",
                    "x-order": "1"
                },
                "startTIme": {
                    "description": "검색 시작 시간",
                    "type": "string",
                    "x-order": "2"
                },
                "endTIme": {
                    "description": "검색 끝 시간",
                    "type": "string",
                    "x-order": "3"
                },
                "predictionCount": {
                    "description": "검색 시간 사이의 총 예측 수",
                    "type": "integer",
                    "x-order": "4"
                }
            }
        },
        "dto.GetDeploymentListResponseDTO": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {},
                "sort": {
                    "type": "string"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalRows": {
                    "type": "integer"
                }
            }
        },
        "dto.GetDeploymentResponseDTO": {
            "type": "object",
            "properties": {
                "featureDriftTracking": {
                    "description": "데이터 드리프트 설정",
                    "type": "string",
                    "x-order": "8",
                    "example": "True"
                },
                "associationID": {
                    "description": "요청데이터에서 ID로 처리할 유일한 피쳐컬럼 명",
                    "type": "string",
                    "x-order": "9",
                    "example": "Index"
                },
                "accuracyAnalyze": {
                    "description": "정확도 측정 설정",
                    "type": "string",
                    "x-order": "9",
                    "example": "True"
                },
                "accuracyStatus": {
                    "type": "string"
                },
                "activeStatus": {
                    "type": "string"
                },
                "changeRequested": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "driftStatus": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "importance": {
                    "type": "string"
                },
                "modelPackageID": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "predictionEnvID": {
                    "type": "string"
                },
                "predictionEnvName": {
                    "type": "string"
                },
                "projectID": {
                    "type": "string"
                },
                "requestCPU": {
                    "type": "number"
                },
                "requestMEM": {
                    "type": "number"
                },
                "serviceHealthStatus": {
                    "type": "string"
                },
                "serviceStatus": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "dto.GetGovernanceHistoryResponseDTO": {
            "type": "object",
            "properties": {
                "eventHistory": {}
            }
        },
        "dto.GetModelHistoryResponseDTO": {
            "type": "object",
            "properties": {
                "modelHistory": {}
            }
        },
        "dto.GetModelPackageListResponseDTO": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "rows": {},
                "sort": {
                    "type": "string"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalRows": {
                    "type": "integer"
                }
            }
        },
        "dto.GetModelPackageResponseDTO": {
            "type": "object",
            "properties": {
                "archived": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "holdoutDatasetName": {
                    "type": "string"
                },
                "modelDescription": {
                    "type": "string"
                },
                "modelFileName": {
                    "type": "string"
                },
                "modelFrameWork": {
                    "type": "string"
                },
                "modelFrameWorkVersion": {
                    "type": "string"
                },
                "modelName": {
                    "type": "string"
                },
                "modelPackageID": {
                    "type": "string"
                },
                "modelVersion": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "negativeClassLabel": {
                    "type": "string"
                },
                "positiveClassLabel": {
                    "type": "string"
                },
                "predictionTargetName": {
                    "type": "string"
                },
                "predictionThreshold": {
                    "type": "number"
                },
                "projectID": {
                    "type": "string"
                },
                "targetType": {
                    "type": "string"
                },
                "trainingDatasetName": {
                    "type": "string"
                }
            }
        },
        "dto.InActiveDeploymentResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.LoginReqDTO": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "captchaID": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResDTO": {
            "type": "object",
            "properties": {
                "expiredAt": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "tokenType": {
                    "type": "string"
                }
            }
        },
        "dto.MonitorAccuracyPatchRequestDTO": {
            "type": "object",
            "properties": {
                "accuracySetting": {
                    "$ref": "#/definitions/dto.PatchAccuracySetting"
                }
            }
        },
        "dto.MonitorAccuracyPatchResponseDTO": {
            "type": "object",
            "properties": {
                "deploymentID": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.MonitorDriftPatchRequestDTO": {
            "type": "object",
            "properties": {
                "dataDriftSetting": {
                    "$ref": "#/definitions/dto.PatchDataDriftSetting"
                }
            }
        },
        "dto.MonitorDriftPatchResponseDTO": {
            "type": "object",
            "properties": {
                "deploymentID": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.MonitorGetSettingResponseDTO": {
            "type": "object",
            "properties": {
                "accuracySetting": {
                    "$ref": "#/definitions/dto.AccuracySetting"
                },
                "dataDriftSetting": {
                    "$ref": "#/definitions/dto.DataDriftSetting"
                }
            }
        },
        "dto.PatchAccuracySetting": {
            "type": "object",
            "properties": {
                "metricType": {
                    "description": "Accuracy 측정 메트릭 종류",
                    "type": "string",
                    "enum": [
                        "rmse",
                        " rmsle",
                        " mae",
                        " mad",
                        " mape",
                        " mean_tweedie_deviance",
                        " gamma_deviance",
                        " tpr",
                        " accuracy",
                        " f1",
                        " ppv",
                        " fnr",
                        " fpr"
                    ],
                    "x-order": "0",
                    "example": "rmse"
                },
                "measurement": {
                    "description": "메트릭 Value 타입",
                    "type": "string",
                    "enum": [
                        "percent",
                        " value"
                    ],
                    "x-order": "1",
                    "example": "percent"
                },
                "atRiskValue": {
                    "description": "메트릭의 AtRisk Value",
                    "type": "number",
                    "x-order": "2",
                    "example": 5
                },
                "failingValue": {
                    "description": "메트릭의 Failing Value",
                    "type": "number",
                    "x-order": "3",
                    "example": 10
                }
            }
        },
        "dto.PatchDataDriftSetting": {
            "type": "object",
            "properties": {
                "monitorRange": {
                    "description": "Monitoring 할 범위",
                    "type": "string",
                    "x-order": "0",
                    "example": "7d"
                },
                "driftMetricType": {
                    "description": "DataDrift 측정 Metric",
                    "type": "string",
                    "x-order": "1",
                    "example": "PSI"
                },
                "driftThreshold": {
                    "description": "Drift 값 임계치",
                    "type": "number",
                    "x-order": "2",
                    "example": 0.15
                },
                "importanceThreshold": {
                    "description": "Importance 값 임계치",
                    "type": "number",
                    "x-order": "3",
                    "example": 0.5
                },
                "lowImportanceAtRiskCount": {
                    "description": "낮은 importance feature 수의 drift at risk 임계치",
                    "type": "integer",
                    "x-order": "4",
                    "example": 1
                },
                "lowImportanceFailingCount": {
                    "description": "낮은 importance feature 수의 drift failing 임계치",
                    "type": "integer",
                    "x-order": "5",
                    "example": 0
                },
                "highImportanceAtRiskCount": {
                    "description": "높은 importance feature 수의 drift at risk 임계치",
                    "type": "integer",
                    "x-order": "6",
                    "example": 0
                },
                "highImportanceFailingCount": {
                    "description": "높은 importance feature 수의 drift failing 임계치",
                    "type": "integer",
                    "x-order": "7",
                    "example": 1
                }
            }
        },
        "dto.RegisterReqDTO": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "captchaID": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.RegisterResDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ReplaceModelRequestDTO": {
            "type": "object",
            "required": [
                "modelPackageID",
                "reason"
            ],
            "properties": {
                "modelPackageID": {
                    "description": "교체 할 모델패키지 ID",
                    "type": "string"
                },
                "reason": {
                    "description": "교체 이유",
                    "type": "string",
                    "enum": [
                        "Accurancy",
                        " DataDrift",
                        " Errors",
                        " ScheduledRefresh",
                        " PredictionSpeed",
                        " Other"
                    ]
                }
            }
        },
        "dto.ReplaceModelResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateAssociationIDRequestDTO": {
            "type": "object",
            "properties": {
                "associationID": {
                    "type": "string",
                    "x-order": "0",
                    "example": "index"
                }
            }
        },
        "dto.UpdateAssociationIDResponseDTO": {
            "type": "object",
            "properties": {
                "deploymentID": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateDeploymentRequestDTO": {
            "type": "object",
            "properties": {
                "importance": {
                    "description": "배포중요도",
                    "type": "string",
                    "enum": [
                        "Low",
                        " Moderate",
                        " High",
                        " Critical"
                    ],
                    "x-order": "5",
                    "example": "Low"
                },
                "requestCPU": {
                    "description": "요청 CPU",
                    "type": "number",
                    "x-order": "6",
                    "example": 1
                },
                "requestMEM": {
                    "description": "요청 MEM",
                    "type": "number",
                    "x-order": "7",
                    "example": 2
                },
                "featureDriftTracking": {
                    "description": "데이터 드리프트 설정",
                    "type": "string",
                    "x-order": "8",
                    "example": "True"
                },
                "associationID": {
                    "description": "요청데이터에서 ID로 처리할 유일한 피쳐컬럼 명",
                    "type": "string",
                    "x-order": "9",
                    "example": "Index"
                },
                "accuracyAnalyze": {
                    "description": "정확도 측정 설정",
                    "type": "string",
                    "x-order": "9",
                    "example": "True"
                },
                "description": {
                    "description": "베포 설명",
                    "type": "string"
                },
                "name": {
                    "description": "베포 명",
                    "type": "string"
                }
            }
        },
        "dto.UpdateDeploymentResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateModelPackageRequestDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "모델패키지 명",
                    "type": "string",
                    "x-order": "1",
                    "example": "ModelPacakge 01"
                },
                "predictionThreshold": {
                    "description": "이진분류 예측임계값",
                    "type": "number",
                    "x-order": "10",
                    "example": 0.5
                },
                "positiveClassLabel": {
                    "description": "이진분류 양성명칭 지정",
                    "type": "string",
                    "x-order": "11",
                    "example": "True"
                },
                "negativeClassLabel": {
                    "type": "string",
                    "x-order": "12",
                    "example": "False"
                },
                "description": {
                    "description": "모델패키지 설명",
                    "type": "string",
                    "x-order": "2",
                    "example": "New ModelPacakge"
                },
                "modelName": {
                    "description": "모델명",
                    "type": "string",
                    "x-order": "3",
                    "example": "Example Model"
                },
                "modelVersion": {
                    "description": "모델 버전",
                    "type": "string",
                    "x-order": "4",
                    "example": "1.4"
                },
                "modelDescription": {
                    "description": "모델 설명",
                    "type": "string",
                    "x-order": "5",
                    "example": "Best Accuracy"
                },
                "targetType": {
                    "description": "모델 예측타입",
                    "type": "string",
                    "enum": [
                        "Binary",
                        " Regression"
                    ],
                    "x-order": "6",
                    "example": "Binary"
                },
                "predictionTargetName": {
                    "description": "예측 타켓명칭",
                    "type": "string",
                    "x-order": "7",
                    "example": "Target"
                },
                "modelFrameWork": {
                    "description": "모델 프레임워크",
                    "type": "string",
                    "enum": [
                        "TensorFlow",
                        " PyTorch",
                        " SkLearn",
                        " XGBoost",
                        " LightGBM"
                    ],
                    "x-order": "8",
                    "example": "TensorFlow"
                },
                "modelFrameWorkVersion": {
                    "description": "모델 프레임워크 버전",
                    "type": "string",
                    "x-order": "9",
                    "example": "1.14.0"
                }
            }
        },
        "dto.UpdateModelPackageResponseDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.UploadActualResponseDTO": {
            "type": "object",
            "properties": {
                "deploymentID": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
