basePath: /api/v1
definitions:
  http.PostModelsRequest:
    properties:
      classLabels:
        description: 멀티클래스분류 일때 라벨
        type: string
      description:
        type: string
      language:
        type: string
      name:
        type: string
      negativeClassLabel:
        description: 이진분류시 거짓값 라벨
        type: string
      positiveClassLabel:
        description: 이진분류시 참값 라벨
        type: string
      predictionThreshold:
        description: 이진분류 모델의 결과가 확률일 때 이진 범주에 매핑
        type: string
      targetType:
        description: Required [‘Binary’, ‘Regression’, ‘Multiclass’, ‘Anomaly’, ‘Transform’,
          ‘Unstructured’]
        type: string
    type: object
  http.PostModelsResponse:
    properties:
      id:
        type: string
    type: object
host: localhost:30000
info:
  contact: {}
  title: KoreServ Swagger API
  version: "1.0"
paths:
  /project/{projectID}/models:
    post:
      consumes:
      - application/json
      description: Create model's info
      parameters:
      - description: name of the model
        in: body
        name: modelBody
        required: true
        schema:
          $ref: '#/definitions/http.PostModelsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.PostModelsResponse'
      summary: Create model
swagger: "2.0"
