definitions:
  dto.ActiveDeploymentResponseDTO:
    properties:
      message:
        type: string
    type: object
  dto.CreateDeploymentRequestDTO:
    properties:
      accuracyAnalyze:
        description: 정확도 측정 설정
        example: true
        type: boolean
        x-order: "9"
      associationID:
        description: 요청데이터에서 ID로 처리할 유일한 피쳐컬럼 명
        example: Index
        type: string
        x-order: "9"
      description:
        description: 배포 설명
        example: deploy best model
        type: string
        x-order: "3"
      featureDriftTracking:
        description: 데이터 드리프트 설정
        example: true
        type: boolean
        x-order: "8"
      importance:
        description: 배포중요도
        enum:
        - Low
        - ' Moderate'
        - ' High'
        - ' Critical'
        example: Low
        type: string
        x-order: "5"
      modelPackageID:
        description: 모델패키지 ID
        example: ID-1234
        type: string
        x-order: 1 x-nullable=false
      name:
        description: 배포 명
        example: This Is a Test Deploy
        type: string
        x-order: 2 x-nullable=false
      predictionEnvID:
        description: 예측 환경
        example: k8s-inference-staging
        type: string
        x-order: "4"
      requestCPU:
        description: 요청 CPU
        example: 1
        type: number
        x-order: "6"
      requestMEM:
        description: 요청 MEM
        example: 2
        type: number
        x-order: "7"
    required:
    - modelPackageID
    - name
    - predictionEnvID
    type: object
  dto.CreateDeploymentResponseDTO:
    properties:
      deploymentID:
        type: string
    type: object
  dto.DeleteDeploymentResponseDTO:
    properties:
      message:
        type: string
    type: object
  dto.GetDeploymentListResponseDTO:
    properties:
      limit:
        type: integer
      page:
        type: integer
      rows: {}
      sort:
        type: string
      totalPages:
        type: integer
      totalRows:
        type: integer
    type: object
  dto.GetDeploymentResponseDTO:
    properties:
      activeStatus:
        type: string
      changeRequested:
        type: boolean
      description:
        type: string
      id:
        type: string
      importance:
        type: string
      modelPackageID:
        type: string
      name:
        type: string
      predictionEnvID:
        type: string
      projectID:
        type: string
      requestCPU:
        type: number
      requestMEM:
        type: number
      serviceStatus:
        type: string
      uri:
        type: string
    type: object
  dto.GetGovernanceHistoryResponseDTO:
    properties:
      eventHistory: {}
    type: object
  dto.GetModelHistoryResponseDTO:
    properties:
      modelHistory: {}
    type: object
  dto.InActiveDeploymentResponseDTO:
    properties:
      message:
        type: string
    type: object
  dto.ReplaceModelRequestDTO:
    properties:
      modelPackageID:
        description: 교체 할 모델패키지 ID
        type: string
      reason:
        description: 교체 이유
        enum:
        - Accurancy
        - ' DataDrift'
        - ' Errors'
        - ' ScheduledRefresh'
        - ' PredictionSpeed'
        - ' Other'
        type: string
    required:
    - modelPackageID
    - reason
    type: object
  dto.ReplaceModelResponseDTO:
    properties:
      message:
        type: string
    type: object
  dto.UpdateDeploymentRequestDTO:
    properties:
      description:
        description: 베포 설명
        type: string
      importance:
        description: 배포중요도
        enum:
        - Low
        - ' Moderate'
        - ' High'
        - ' Critical'
        example: Low
        type: string
        x-order: "5"
      name:
        description: 베포 명
        type: string
    type: object
  dto.UpdateDeploymentResponseDTO:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /deployments:
    get:
      consumes:
      - application/json
      description: 배포 리스트
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: queryName
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      - description: sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetDeploymentListResponseDTO'
      summary: Get Deployment List
      tags:
      - Deployment
  /deployments/{deploymentID}:
    get:
      consumes:
      - application/json
      description: 배포 상세조회
      parameters:
      - description: projectID
        in: path
        name: projectID
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetDeploymentResponseDTO'
      summary: Get Deployment
      tags:
      - Deployment
  /deployments/{deploymentID}/governance-log:
    get:
      consumes:
      - application/json
      description: 배포 거버넌스 로그 조회
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetGovernanceHistoryResponseDTO'
      summary: Get Governance Log
      tags:
      - Deployment
  /deployments/{deploymentID}/model-history:
    get:
      consumes:
      - application/json
      description: 배포 모델 변경이력 조회
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetModelHistoryResponseDTO'
      summary: Get Model History
      tags:
      - Deployment
  /deployments/{deploymentID}/predict:
    post:
      consumes:
      - application/json
      description: 예측 요청
      parameters:
      - description: projectID
        in: path
        name: projectID
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      - description: application/json
        in: body
        name: json
        required: true
        schema:
          example: '{"association_id": ["abcd1234", "abcd1235"], "instances": [[1.483887,
            1.865988, 2.234620, 1.018782, -2.530891, -1.604642, 0.774676, -0.465148,
            -0.495225], [1.483887, 1.865988, 2.234620, 1.018782, -2.530891, -1.604642,
            0.774676, -0.465148, -0.495225]]}'
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ReplaceModelResponseDTO'
      summary: Send Prediction
      tags:
      - Deployment
  /deployments/{deploymentID}/replace-model:
    patch:
      consumes:
      - application/json
      description: 배포 모델변경
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      - description: Create Deployment
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ReplaceModelRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ReplaceModelResponseDTO'
      summary: Replace Model
      tags:
      - Deployment
  /projects/{projectID}/deployments:
    get:
      consumes:
      - application/json
      description: 배포 리스트
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: queryName
        in: query
        name: name
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      - description: sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetDeploymentListResponseDTO'
      summary: Get Deployment List
      tags:
      - Deployment
    post:
      consumes:
      - application/json
      description: 배포 생성
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: Create Deployment
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDeploymentRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateDeploymentResponseDTO'
      summary: Create Deployment
      tags:
      - Deployment
  /projects/{projectID}/deployments/{deploymentID}:
    delete:
      consumes:
      - application/json
      description: 배포 삭제
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DeleteDeploymentResponseDTO'
      summary: Delete Deployment
      tags:
      - Deployment
    get:
      consumes:
      - application/json
      description: 배포 상세조회
      parameters:
      - description: projectID
        in: path
        name: projectID
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetDeploymentResponseDTO'
      summary: Get Deployment
      tags:
      - Deployment
    patch:
      consumes:
      - application/json
      description: 배포 정보수정
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      - description: Update Deployment Info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateDeploymentRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateDeploymentResponseDTO'
      summary: Edit Deployment
      tags:
      - Deployment
  /projects/{projectID}/deployments/{deploymentID}/active:
    put:
      consumes:
      - application/json
      description: 배포 활성화
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ActiveDeploymentResponseDTO'
      summary: Active Deployment
      tags:
      - Deployment
  /projects/{projectID}/deployments/{deploymentID}/governance-log:
    get:
      consumes:
      - application/json
      description: 배포 거버넌스 로그 조회
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetGovernanceHistoryResponseDTO'
      summary: Get Governance Log
      tags:
      - Deployment
  /projects/{projectID}/deployments/{deploymentID}/inactive:
    put:
      consumes:
      - application/json
      description: 배포 비활성화
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.InActiveDeploymentResponseDTO'
      summary: Inactive Deployment
      tags:
      - Deployment
  /projects/{projectID}/deployments/{deploymentID}/model-history:
    get:
      consumes:
      - application/json
      description: 배포 모델 변경이력 조회
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetModelHistoryResponseDTO'
      summary: Get Model History
      tags:
      - Deployment
  /projects/{projectID}/deployments/{deploymentID}/predict:
    post:
      consumes:
      - application/json
      description: 예측 요청
      parameters:
      - description: projectID
        in: path
        name: projectID
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      - description: application/json
        in: body
        name: json
        required: true
        schema:
          example: '{"association_id": ["abcd1234", "abcd1235"], "instances": [[1.483887,
            1.865988, 2.234620, 1.018782, -2.530891, -1.604642, 0.774676, -0.465148,
            -0.495225], [1.483887, 1.865988, 2.234620, 1.018782, -2.530891, -1.604642,
            0.774676, -0.465148, -0.495225]]}'
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ReplaceModelResponseDTO'
      summary: Send Prediction
      tags:
      - Deployment
  /projects/{projectID}/deployments/{deploymentID}/replace-model:
    patch:
      consumes:
      - application/json
      description: 배포 모델변경
      parameters:
      - description: projectID
        in: path
        name: projectID
        required: true
        type: string
      - description: deploymentID
        in: path
        name: deploymentID
        required: true
        type: string
      - description: Create Deployment
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ReplaceModelRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ReplaceModelResponseDTO'
      summary: Replace Model
      tags:
      - Deployment
swagger: "2.0"
